### ISSUE TITLE
启动运行报错

### ISSUE THREAD

**Issue by tom-hanks** [TaiAiAc/vue3-vite-ts-uniapp#1]
运行报错啊
[vite] [plugin:vite:import-analysis] Failed to resolve import "./pages/login/pages/main/index.vue" from "src/pages-json-js". Does the file exist?
at pages-json-js:89:51
  87 |  const PagesTabBarExtUIExtUILoader = ()=>import('./pages/tab-bar/extUI/extUI.vue').then(com => setupPage(com.default || com))
  88 |  const PagesTabBarExtUIExtUI = defineAsyncComponent(extend({loader:PagesTabBarExtUIExtUILoader},AsyncComponentOptions))
  89 |  const PagesLoginPagesMainIndexLoader = ()=>import('./pages/login/pages/main/index.vue').then(com => setupPage(com.default || com))
     |                                                    ^
  90 |  const PagesLoginPagesMainIndex = defineAsyncComponent(extend({loader:PagesLoginPagesMainIndexLoader},AsyncComponentOptions))
  91 |

**Comment by TaiAiAc** [comment]
1. 用 pnpm 包管理器 
2. 升级一下 uniapp 的依赖 npx @dcloudio/uvm@latest

**Comment by TaiAiAc** [comment]
这个很久没更新了 给你推荐个好用的模板吧 https://codercup.github.io/unibest-docs/

**Comment by TaiAiAc** [comment]
是分包页面没加上 创建对应的分包路径就 ok 了 已经提交了
